// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHtaPAvsnYF_hx1mORtib9JrdE7u_RyRI',
    appId: '1:433804596993:web:798c89a9a907b66983ad00',
    messagingSenderId: '433804596993',
    projectId: 'qtech-dashboard-taks',
    authDomain: 'qtech-dashboard-taks.firebaseapp.com',
    measurementId: 'G-M7DRB34SGJ',
    databaseURL: 'https://qtech-dashboard-taks-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Z9TslXqM1AyFuFZMhbIYp1zCg0ObNm4',
    appId: '1:433804596993:android:244588b730940d1283ad00',
    messagingSenderId: '433804596993',
    projectId: 'qtech-dashboard-taks',
    databaseURL: 'https://qtech-dashboard-taks-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv4R2fZtxNLiZaL4psyyXiCU-64W7t-18',
    appId: '1:433804596993:ios:2306afb5b9805cdc83ad00',
    messagingSenderId: '433804596993',
    projectId: 'qtech-dashboard-taks',
    iosBundleId: 'com.example.dashboardQtechTask',
    databaseURL: 'https://qtech-dashboard-taks-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv4R2fZtxNLiZaL4psyyXiCU-64W7t-18',
    appId: '1:433804596993:ios:2306afb5b9805cdc83ad00',
    messagingSenderId: '433804596993',
    projectId: 'qtech-dashboard-taks',
    iosBundleId: 'com.example.dashboardQtechTask',
    databaseURL: 'https://qtech-dashboard-taks-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHtaPAvsnYF_hx1mORtib9JrdE7u_RyRI',
    appId: '1:433804596993:web:b319e7e7168e73fd83ad00',
    messagingSenderId: '433804596993',
    projectId: 'qtech-dashboard-taks',
    authDomain: 'qtech-dashboard-taks.firebaseapp.com',
    measurementId: 'G-HG5WFSTRST',
    databaseURL: 'https://qtech-dashboard-taks-default-rtdb.europe-west1.firebasedatabase.app',
  );
}
